version: "3"

services:
  orion:
    image: fiware/orion:2.5.0
    ports:
      - "1026:1026"
    depends_on:
      - mongo
    command: -dbhost mongo

  orion-ld:
    image: fiware/orion-ld:latest
    ports:
      - "11026:1026"
    depends_on:
      - mongo
    command: -dbhost mongo -db orionld

  mongo:
    image: mongo:3.6
    command: --nojournal
