name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test:
    name: build test

    runs-on: ubuntu-latest

    env:
      TZ: Asia/Tokyo

    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Checkout dependencies
      run: |
        go get github.com/x-motemen/gobump/cmd/gobump
        make devel-deps

    - name: Build NGSI Go
      run: make build

  unit-test:
    name: unit test

    runs-on: ubuntu-latest

    env:
      TZ: Asia/Tokyo

    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Checkout dependencies
      run: |
        go get github.com/x-motemen/gobump/cmd/gobump
        make devel-deps

    - name: Test NGSI Go
      run: make test

    - name: Convert coverage to lcov
      uses: jandelgado/gcov2lcov-action@v1.0.8
      with:
        working-directory: coverage

    - name: Coveralls
      uses: coverallsapp/github-action@v1.1.2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: coverage/coverage.lcov

  e2e-test:
    name: e2e test

    runs-on: ubuntu-latest

    env:
      TZ: Asia/Tokyo

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run e2e test
      run: make e2e_test

  lint-dockerfile:
    name: Lint Dockerfile
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Run Hadolint Dockerfile Linter
        uses: burdzwastaken/hadolint-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HADOLINT_ACTION_DOCKERFILE_FOLDER: docker

      - name: Run Hadolint Dockerfile Linter
        uses: burdzwastaken/hadolint-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HADOLINT_ACTION_DOCKERFILE_FOLDER: e2e/ngsi-test

      - name: Run Hadolint Dockerfile Linter
        uses: burdzwastaken/hadolint-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HADOLINT_ACTION_DOCKERFILE_FOLDER: e2e/server/accumulator

      - name: Run Hadolint Dockerfile Linter
        uses: burdzwastaken/hadolint-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HADOLINT_ACTION_DOCKERFILE_FOLDER: e2e/server/atcontext

      - name: Run Hadolint Dockerfile Linter
        uses: burdzwastaken/hadolint-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HADOLINT_ACTION_DOCKERFILE_FOLDER: e2e/server/csource

      - name: Run Hadolint Dockerfile Linter
        uses: burdzwastaken/hadolint-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HADOLINT_ACTION_DOCKERFILE_FOLDER: e2e/server/oauth
